### ISSUE TITLE
pyoperon @cpp17 cannot be installed

### ISSUE THREAD

**Issue by ghost** [erusseil/MvSR-analysis#5]
**How did you install pyoperon with no problem? I'm using the command below:**

!pip3 install git+https://github.com/heal-research/pyoperon.git@cpp17

**But receiving this error (tried to install locally and on google colab, but doesn't work on none of them):**
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['nix', 'cmake', 'ports', 'docker', 'source', 'include', 'pyoperon'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
...
│ exit code: 1
╰─> See above for output.

**Comment by folivetti** [comment]
Hi, you can download the pyoperon wheel supporting aggregation in this link https://github.com/heal-research/pyoperon/releases

After that you can just `pip install <wheel-filename>`

Let me know if that works!

**Comment by ghost** [comment]
Hi, I downloaded two versions of the wheels and tried to install them, but getting this error:
ERROR: pyoperon-0.3.6-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
I'm not still sure if I have done it correctly.

It might be easy from your side, sorry for asking basic questions. 
But I'm confused with the whole process of installing pyoperon (not as experienced as you in python, but keen to use MvSR as a part of my work). Could you please instruct me step-by-step on how to install pyoperon so that's compatible with MvSR? I'm using python 3.7.9, 3.10, and 3.11 in different conda environments (windows). Much appreciate your help!

**Comment by folivetti** [comment]
no worries, we're glad to help :-)

I'm afraid these wheels only work on Linux. I'll try to figure it out if there are any recent wheel compatible with Windows.

One thing you can do is use windows WSL to have a working Linux environment inside your windows.

**Comment by ghost** [comment]
Thanks very much. I will explore to see how a virtual Linux environment works.

**Comment by folivetti** [comment]
if you need help with that, let us know. In the meantime I'll check a windows alternative and, if I find something, I'll let you know

**Comment by ghost** [comment]
**Thanks very much for your help. I managed to install pyoperon 0.3.6 using wsl in windows and the library now works properly. I am trying to run the example absorption.ipynb and I am receiving the following error:**

{
	"name": "TypeError",
	"message": "__init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyoperon.pyoperon.Evaluator(arg0: Operon::Problem, arg1: pyoperon.pyoperon.Interpreter, arg2: pyoperon.pyoperon.ErrorMetric, arg3: bool)

Invoked with: <pyoperon.pyoperon.Problem object at 0x7f360801c7f0>, <pyoperon.pyoperon.DispatchTable object at 0x7f360801d170>, <pyoperon.pyoperon.MSE object at 0x7f36093877f0>, True",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 agg_best_str, all_best_str = mvsr.MultiViewSR(folder, maxL=15, maxD=3, generations=1000, seed=5,
      2                                               OperationSet=Operon.NodeType.Exp|Operon.NodeType.Log, verbose=False, explicit_params=False)
      4 func, func_str, initial_guess = ana.convert_string_to_func(agg_best_str, 1)
      5 func_str

File ~/Codes/MvSR-analysis-main/real_data/mvsr.py:121, in MultiViewSR(path, minL, maxL, maxD, generations, OperationSet, seed, verbose, use_single_view, explicit_params)
    119 error_metric = Operon.MSE()  # use the coefficient of determination as fitness
    120 metrics.append(error_metric)
--> 121 evaluator_i = Operon.Evaluator(problems[i], 
    122                                interpreter, 
    123                                metrics[-1], 
    124                                True)
    125 optimizers.append(
    126     Operon.Optimizer(
    127         interpreter,
   (...)
    133     )
    134 )
    136 evaluator_i.Optimizer = optimizers[-1]

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyoperon.pyoperon.Evaluator(arg0: Operon::Problem, arg1: pyoperon.pyoperon.Interpreter, arg2: pyoperon.pyoperon.ErrorMetric, arg3: bool)

Invoked with: <pyoperon.pyoperon.Problem object at 0x7f360801c7f0>, <pyoperon.pyoperon.DispatchTable object at 0x7f360801d170>, <pyoperon.pyoperon.MSE object at 0x7f36093877f0>, True"
}

It seems to happen in the mvsr.py when running the following line in the example:
agg_best_str, all_best_str = mvsr.MultiViewSR(folder, maxL=15, maxD=3, generations=1000, seed=5,
                                              OperationSet=Operon.NodeType.Exp|Operon.NodeType.Log, verbose=False, explicit_params=False)

**Could** you please help to see where the error is coming from? I haven't changed anything in the code. 

**I thought this might be resolved by installing the cpp17 branch, as mentioned. But when directly cloning the cpp17 branch (using git clone) and then "pip install .", it will install as UNKNOWN library. I also tried to specify a name by adding "#egg=pyoperon" at the end of git clone implementation, but it gives an error saying that metadata is UNKNOWN. I don't exactly know how to install this branch using pip.**

**Thanks again!**

**Comment by folivetti** [comment]
have you installed using the wheels that I mentioned in the first answer?
The correct procedure to have the MvSR feature is using

`pip install pyoperon-0.3.6-cp38-cp38-linux_x86_64.whl` 

for example. You should choose the cp that matches your python (cp38 = python 3.8).
Let me know if that solves the issue. Otherwise, try to write here step-by-step how you installed everything so I can try to replicate

**Comment by ghost** [comment]
(1) Yes, I used 

`pip install https://github.com/heal-research/pyoperon/releases/download/v0.3.6/pyoperon-0.3.6-cp310-cp310-linux_x86_64.whl`

as I am using python 3.10.12 on Ubuntu, and received the following message on the successful installation of pyoperon 3.6:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting pyoperon==0.3.6
  Downloading https://github.com/heal-research/pyoperon/releases/download/v0.3.6/pyoperon-0.3.6-cp310-cp310-linux_x86_64.whl (946 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 946.9/946.9 KB 7.1 MB/s eta 0:00:00
Installing collected packages: pyoperon
Successfully installed pyoperon-0.3.6
```
**Checking the list of packages using Pip list, I can see now pyoperon  0.3.6 has been installed**

(2) Next, I made the recommended changes in iminuit 2.24 as mentioned in the first requirement for MvSR (https://github.com/erusseil/MvSR-analysis).

(3) Then, I cloned the https://github.com/erusseil/MvSR-analysis:

`git clone https://github.com/erusseil/MvSR-analysis`

(4) Next, I changed the directory to the cloned repository and installed reqiurements.txt.  

`pip install -r requirement.txt`

(5) Then, I changed the directory again to MvSR-analysis-main/real_data and opened absorption.ipynb

And when running cell by cell, it works fine in the first 2 cells (importing libraries and format data). Then I receive the abovementioned error in the Run MvSR cell. 

```
{
	"name": "TypeError",
	"message": "__init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyoperon.pyoperon.Evaluator(arg0: Operon::Problem, arg1: pyoperon.pyoperon.Interpreter, arg2: pyoperon.pyoperon.ErrorMetric, arg3: bool)

Invoked with: <pyoperon.pyoperon.Problem object at 0x7f6429410db0>, <pyoperon.pyoperon.DispatchTable object at 0x7f6428e987b0>, <pyoperon.pyoperon.MSE object at 0x7f64a429ca30>, True",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 agg_best_str, all_best_str = mvsr.MultiViewSR(folder, maxL=15, maxD=3, generations=1000, seed=5,
      2                                               OperationSet=Operon.NodeType.Exp|Operon.NodeType.Log, verbose=False, explicit_params=False)
      4 func, func_str, initial_guess = ana.convert_string_to_func(agg_best_str, 1)
      5 func_str

File ~/Codes/MvSR-analysis-main/real_data/../mvsr.py:120, in MultiViewSR(path, minL, maxL, maxD, generations, OperationSet, seed, verbose, use_single_view, explicit_params)
    118 error_metric = Operon.MSE()  # use the coefficient of determination as fitness
    119 metrics.append(error_metric)
--> 120 evaluator_i = Operon.Evaluator(problems[i], interpreter, metrics[-1], True)
    121 optimizers.append(
    122     Operon.Optimizer(
    123         interpreter,
   (...)
    129     )
    130 )
    132 evaluator_i.Optimizer = optimizers[-1]

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyoperon.pyoperon.Evaluator(arg0: Operon::Problem, arg1: pyoperon.pyoperon.Interpreter, arg2: pyoperon.pyoperon.ErrorMetric, arg3: bool)

Invoked with: <pyoperon.pyoperon.Problem object at 0x7f6429410db0>, <pyoperon.pyoperon.DispatchTable object at 0x7f6428e987b0>, <pyoperon.pyoperon.MSE object at 0x7f64a429ca30>, True"
}
```

**Comment by folivetti** [comment]
alright, I found the issue and I'm in contact with @foolnotion to check what we have to change in mvsr.py

Meanwhile, you can use the wheels stored in this zip file. They seem to work fine for me. As soon as we find a definite solution we'll update the scripts and let you know.

[pyoperon-wheel.zip](https://github.com/erusseil/MvSR-analysis/files/14389428/pyoperon-wheel.zip)

**Comment by ghost** [comment]
I works with the wheels you provided! THANKS A LOT!

**Comment by folivetti** [comment]
great! If you have any other questions just open a new issue, we'll be glad to help :-)

I'll update the instructions later with the wheels on this zip file so nobody else has any problem.
